### ISSUE TITLE
jquery-ui.js missing from 1.11.0 bower package

### ISSUE THREAD

**Issue by thgreasi** [components/jqueryui#32]
I don't know if I`missing something, but it looks like jquery-ui.js and jquery-ui.min.js are missing from both the bower installation I just attempted and the [1.11.0 release tag archives](https://github.com/components/jqueryui/releases/tag/1.11.0).

_tl;dr_ `ui/jquery-ui.js` as specified in bower.json is missing from bower package for v1.11.0

**Comment by jhourlad** [comment]
Not fixed. Still missing.
