### ISSUE TITLE
minified files can't be resolved

### ISSUE THREAD

**Issue by JoniJnm** [components/jqueryui#52]
How can I use minified files?

The files are in the folder:

/ui/minified/

For example, the file autocomplete.min.js:
`define(["jquery","./core","./widget","./position","./menu"],t)`

has dependences which can't be resolved because the min files has the suffix "min" (core.js doesn't exists, the name is core.min.js).

This can be fixed if you don't add the suffix "min" to files in minified folder.

**Comment by mrohnstock** [comment]
As I noticed, this should be fixed with 1.12.0 at least, as all files got renamed to the correct names.
