### ISSUE TITLE
Missing CSS files

### ISSUE THREAD

**Issue by amk221** [components/jqueryui#56]
I used to be able to individually include `base/core.css` and `base/datepicker.css` into my app.
These are still present in 1.12.0 of [jquery-ui](https://github.com/jquery/jquery-ui/tree/master/themes/base) but are not in this shim repo.

**Comment by sylfabre** [comment]
+1

**Comment by mrohnstock** [comment]
hm... how could this happen...? I will add theme ASAP.

**Comment by mrohnstock** [comment]
done, sorry about that.

**Comment by sylfabre** [comment]
@mrohnstock Thanks !

**Comment by sylfabre** [comment]
@mrohnstock Could you make a new release with a different version number?

**Comment by mrohnstock** [comment]
done, 1.12.0.1

**Comment by sylfabre** [comment]
@mrohnstock Merci !
