### ISSUE TITLE
1.12.0 moves files under ui?

### ISSUE THREAD

**Issue by plynchnlm** [components/jqueryui#57]
I would have expected 1.12.0 not to have breaking changes.  However, many files were moved from ui to ui/widgets.  Per the [documentation](https://learn.jquery.com/jquery-ui/environments/bower/) on using jquery-ui with bower, we are encouraged to use just the parts of jquery-ui our app needs to avoid downloading the whole thing.  One example of such a link is given as:

```html
<script src="bower_components/jquery-ui/ui/accordion.js"></script>
```

which now won't work, because accordion.js has been moved.

**Comment by mrohnstock** [comment]
yeah, jquery-ui made this change upstream, as you can see, if you take a look in their [master (1.12)](https://github.com/jquery/jquery-ui/tree/master/ui) and [1.11](https://github.com/jquery/jquery-ui/tree/1-11-stable/ui) branch.

This is something you should report [upstream](https://github.com/jquery/jquery-ui) directly.

**Comment by plynchnlm** [comment]
It turns out that they don't follow semver yet.  See https://bugs.jqueryui.com/ticket/10133.
