### ISSUE TITLE
showCurrentAtPos problem

### ISSUE THREAD

**Issue by minerbog** [components/jqueryui#65]
The 'showCurrentAtPos' parameter cause unexpected problems with the multi-month view. The prev button fails to work. The next button forwards 3 months at a time and when clicking any date it acts like the prev button should.

**Comment by mrohnstock** [comment]
This is the wrong place to report jqueryui bugs, as this is only the shim repository.

Visit http://jqueryui.com/support/ and let the devs know about your issue - thanks :).
